module ApacheDefaultValues where

import TypeFiles.ApacheTypes

data DefaultValues = DefaultValues { 

    d_AcceptFilter :: String, 
    d_AcceptPathInfo :: String, 
    d_AccessFileName :: String, 
    d_AddDefaultCharset :: String, 
    d_AllowEncodedSlashes :: String, 
    d_AllowOverride :: String, 
    d_AllowOverrideList :: String, 
    d_ContentDigest :: String, 
    d_DefaultRuntimeDir :: String, 
    d_Define :: String,  
    d_DocumentRoot :: String, 
    d_EnableMMAP :: String, 
    d_EnableSendfile :: String, 
    d_Error :: String, 
    d_ErrorDocument :: String, 
    d_ErrorLog :: String, 
    d_ErrorLogFormat :: String, 
    d_ExtendedStatus :: String, 
    d_FileEtag :: String, 
    d_ForceType :: String, 
    d_HostnameLookups :: String, 
    d_Include :: String, 
    d_IncludeOptional :: String, 
    d_KeepAlive :: String, 
    d_KeepAliveTimeout :: String, 
    d_LimitInternalRecursion :: String, 
    d_LimitRequestBody :: String, 
    d_LimitRequestFields :: String, 
    d_LimitRequestFieldSize :: String, 
    d_LimitRequestLine :: String, 
    d_LimitXMLRequestBody :: String, 
    d_LogLevel :: String, 
    d_MaxKeepAliveRequests :: String, 
    d_MaxRangeOverlaps :: String, 
    d_MaxRangeReversals :: String, 
    d_MaxRanges :: String, 
    d_Mutex :: String, 
    d_Options :: String, 
    d_Protocol :: String, 
    d_RLimitCPU :: String, 
    d_RLimitMEM :: String, 
    d_RLimitNPROC :: String, 
    d_SeeRequestTail :: String, 
    d_ServerAdmin :: String, 
    d_ServerAlias :: String, 
    d_ServerName :: String, 
    d_ServerPath :: String, 
    d_ServerRoot :: String, 
    d_ServerSignature :: String, 
    d_ServerTokens :: String, 
    d_SetHandler :: String, 
    d_SetInputFilter :: String, 
    d_SetOutputFilter :: String, 
    d_TimeOut :: String, 
    d_TraceEnable :: String, 
    d_UnDefine :: String, 
    d_UseCanonicalName :: String, 
    d_UseCanonicalPhysicalPort :: String, 
    
    d_GracefulShutdownTimeout :: String, 
    d_Listen :: String, 
    d_ListenBackLog :: String, 
    d_MaxConnectionsPerChild :: String, 
    d_MaxMemFree :: String, 
    d_MaxRequestWorkers :: String, 
    d_PidFile :: String, 
    d_ReceiveBufferSize :: String, 
    d_ScoreBoardFile :: String, 
    d_SendBufferSize :: String, 
    d_ServerLimit :: String, 
    d_StartServers :: String, 
    d_MaxSpareServers :: String, 
    d_MinSpareServers :: String, 
    
    d_Alias :: String, 
    d_AliasMatch :: String, 
    d_Redirect :: String, 
    d_RedirectMatch :: String, 
    d_RedirectPermanent :: String, 
    d_RedirectTemp :: String, 
    d_ScriptAlias :: String, 
    d_ScriptAliasMatch :: String, 

    d_AuthBasicAuthoritative :: String, 
    d_AuthBasicFake :: String, 
    d_AuthBasicProvider :: String, 
    d_AuthBasicUseDigestAlgorithm :: String, 

    d_AuthName :: String, 
    d_AuthType :: String, 

    d_AuthUserFile :: String, 

    d_AuthMerging :: String, 
    d_AuthzSendForbiddenOnFailure :: String, 
    d_Require :: String, 

    d_AuthGroupFile :: String, 

    d_AddAlt :: String, 
    d_AddAltByEncoding :: String, 
    d_AddAltByType :: String, 
    d_AddDescription :: String, 
    d_AddIcon :: String, 
    d_AddIconByEncoding :: String, 
    d_AddIconByType :: String, 
    d_DefaultIcon :: String, 
    d_HeaderName :: String, 
    d_IndexHeadInsert :: String, 
    d_IndexIgnore :: String, 
    d_IndexIgnoreReset :: String, 
    d_IndexOptions :: String, 
    d_IndexOrderDefault :: String, 
    d_IndexStyleSheet :: String, 
    d_ReadmeName :: String, 
    
    d_ScriptLog :: String, 
    d_ScriptLogBuffer :: String, 
    d_ScriptLogLength :: String, 
    
    d_ScriptSock :: String, 
    d_CGIDScriptTimeout :: String, 
    
    d_DirectoryCheckHandler :: String, 
    d_DirectoryIndex :: String, 
    d_IndexRedirect :: String, 
    d_DirectorySlash :: String, 
    d_FallbackResource :: String, 
    
    d_PassEnv :: String, 
    d_SetEnv :: String, 
    d_UnsetEnv :: String, 
    
    d_AddOutputFilterByType :: String, 
    d_FilterChain :: String, 
    d_FilterDeclare :: String, 
    d_FilterProtocol :: String, 
    d_FilterProvider :: String, 
    d_FilterTrace :: String, 
    
    d_ImapBase :: String, 
    d_ImapDefault :: String, 
    d_ImapMenu :: String, 
    
    d_BufferedLogs :: String, 
    d_CustomLog :: String, 
    d_LogFormat :: String, 
    d_TransferLog :: String, 
    
    d_AddCharset :: String, 
    d_AddEncoding :: String, 
    d_AddHandler :: String, 
    d_AddInputFilter :: String, 
    d_AddLanguage :: String, 
    d_AddOutputFilter :: String, 
    d_AddType :: String, 
    d_DefaultLanguage :: String, 
    d_ModMimeUsePathInfo :: String, 
    d_MultiviewsMatch :: String, 
    d_RemoveCharset :: String, 
    d_RemoveEncoding :: String,
    d_RemoveHandler :: String, 
    d_RemoveInputFilter :: String, 
    d_RemoveLanguage :: String,
    d_RemoveOutputFilter :: String, 
    d_RemoveType :: String, 
    d_TypesConfig :: String, 
    
    d_CacheNegotiatedDocs :: String, 
    d_ForceLanguagePriority :: String, 
    d_LanguagePriority :: String, 
    
    d_ReflectorHeader :: String, 

    d_KeptBodySize :: String, 
    
    d_BrowserMatch :: String, 
    d_BrowserMatchNoCase :: String, 
    d_SetEnvIf :: String, 
    d_SetEnvIfExpr :: String, 
    d_SetEnvIfNoCase :: String, 
    
    d_ChrootDir :: String, 
    d_Group :: String, 
    d_Suexec :: String, 
    d_User :: String, 
    
    d_UserDir :: String, 
    
    d_SSLCACertificateFile :: String, 
    d_SSLCACertificatePath :: String, 
    d_SSLCADNRequestFile :: String, 
    d_SSLCADNRequestPath :: String, 
    d_SSLCARevocationCheck :: String, 
    d_SSLCARevocationFile :: String, 
    d_SSLCARevocationPath :: String, 
    d_SSLCertificateChainFile :: String, 
    d_SSLCertificateFile :: String, 
    d_SSLCertificateKeyFile :: String, 
    d_SSLCipherSuite :: String, 
    d_SSLCompression :: String, 
    d_SSLCryptoDevice :: String, 
    d_SSLEngine :: String, 
    d_SSLFIPS :: String, 
    d_SSLHonorCipherOrder :: String, 
    d_SSLInsecureRenegotiation :: String, 
    d_SSLOCSPDefaultResponder :: String, 
    d_SSLOCSPEnable :: String, 
    d_SSLOCSPOverrideResponder :: String, 
    d_SSLOCSPResponderTimeout :: String, 
    d_SSLOCSPResponseMaxAge :: String, 
    d_SSLOCSPResponseTimeSkew :: String, 
    d_SSLOCSPUseRequestNonce :: String, 
    d_SSLOpenSSLConfCmd :: String, 
    d_SSLOptions :: String, 
    d_SSLPassPhraseDialog :: String, 
    d_SSLProtocol :: String, 
    d_SSLRandomSeed :: String, 
    d_SSLRenegBufferSize :: String, 
    d_SSLRequireSSL :: String,
    d_SSLSessionCache :: String, 
    d_SSLSessionCacheTimeout :: String, 
    d_SSLSessionTicketKeyFile :: String, 
    d_SSLSessionTickets :: String, 
    d_SSLSRPUnknownUserSeed :: String, 
    d_SSLSRPVerifierFile :: String, 
    d_SSLStaplingCache :: String, 
    d_SSLStaplingErrorCacheTimeout :: String, 
    d_SSLStaplingFakeTryLater :: String, 
    d_SSLStaplingForceURL :: String, 
    d_SSLStaplingResponderTimeout :: String, 
    d_SSLStaplingResponseMaxAge :: String, 
    d_SSLStaplingResponseTimeSkew :: String, 
    d_SSLStaplingReturnResponderErrors :: String, 
    d_SSLStaplingStandardCacheTimeout :: String, 
    d_SSLStrictSNIVHostCheck :: String, 
    d_SSLUseStapling :: String, 
    d_SSLVerifyClient :: String, 
    d_SSLVerifyDepth :: String, 
    d_SSLUserName :: String

} deriving (Show)

defaults :: DefaultValues
defaults = DefaultValues {

    d_AcceptFilter = "", 
    d_AcceptPathInfo = "Default", 
    d_AccessFileName = ".htaccess", 
    d_AddDefaultCharset = "Off", 
    d_AllowEncodedSlashes = "Off", 
    d_AllowOverride = "None", 
    d_AllowOverrideList = "None", 
    d_ContentDigest = "Off", 
    d_DefaultRuntimeDir = "DEFAULT_REL_RUNTIMEDIR", 
    d_Define = "",
    d_DocumentRoot = "/usr/local/apache/htdocs", 
    d_EnableMMAP = "On", 
    d_EnableSendfile = "Off", 
    d_Error = "", 
    d_ErrorDocument = "", 
    d_ErrorLog = "logs/error_log", 
    d_ErrorLogFormat = "", 
    d_ExtendedStatus = "Off", 
    d_FileEtag = "MTime Size", 
    d_ForceType = "", 
    d_HostnameLookups = "Off", 
    d_Include = "", 
    d_IncludeOptional = "", 
    d_KeepAlive = "On", 
    d_KeepAliveTimeout = "5", 
    d_LimitInternalRecursion = "10 10", 
    d_LimitRequestBody = "0", 
    d_LimitRequestFields = "100", 
    d_LimitRequestFieldSize = "8190", 
    d_LimitRequestLine = "8190", 
    d_LimitXMLRequestBody = "1000000", 
    d_LogLevel = "warn", 
    d_MaxKeepAliveRequests = "100", 
    d_MaxRangeOverlaps = "20", 
    d_MaxRangeReversals = "20", 
    d_MaxRanges = "200", 
    d_Mutex = "default", 
    d_Options = "FollowSymLinks", 
    d_Protocol = "", 
    d_RLimitCPU = "", 
    d_RLimitMEM = "", 
    d_RLimitNPROC = "", 
    d_SeeRequestTail = "Off", 
    d_ServerAdmin = "", 
    d_ServerAlias = "", 
    d_ServerName = "", 
    d_ServerPath = "", 
    d_ServerRoot = "/usr/local/apache", 
    d_ServerSignature = "Off", 
    d_ServerTokens = "Full", 
    d_SetHandler = "", 
    d_SetInputFilter = "", 
    d_SetOutputFilter = "", 
    d_TimeOut = "60", 
    d_TraceEnable = "On", 
    d_UnDefine = "", 
    d_UseCanonicalName = "Off", 
    d_UseCanonicalPhysicalPort = "Off", 
    
    d_GracefulShutdownTimeout = "0", 
    d_Listen = "", 
    d_ListenBackLog = "511", 
    d_MaxConnectionsPerChild = "0", 
    d_MaxMemFree = "2048", 
    d_MaxRequestWorkers = "256", 
    d_PidFile = "logs/http.pid", 
    d_ReceiveBufferSize = "0", 
    d_ScoreBoardFile = "logs/apache_runtime_status", 
    d_SendBufferSize = "0", 
    d_ServerLimit = "256", 
    d_StartServers = "5", 
    d_MaxSpareServers = "10", 
    d_MinSpareServers = "5", 
    
    d_Alias = "", 
    d_AliasMatch = "", 
    d_Redirect = "", 
    d_RedirectMatch = "", 
    d_RedirectPermanent = "", 
    d_RedirectTemp = "", 
    d_ScriptAlias = "", 
    d_ScriptAliasMatch = "", 

    d_AuthBasicAuthoritative = "On", 
    d_AuthBasicFake = "", 
    d_AuthBasicProvider = "file", 
    d_AuthBasicUseDigestAlgorithm = "Off", 

    d_AuthName = "", 
    d_AuthType = "", 

    d_AuthUserFile = "", 

    d_AuthMerging = "Off", 
    d_AuthzSendForbiddenOnFailure = "Off", 
    d_Require = "", 

    d_AuthGroupFile = "", 

    d_AddAlt = "", 
    d_AddAltByEncoding = "", 
    d_AddAltByType = "", 
    d_AddDescription = "", 
    d_AddIcon = "", 
    d_AddIconByEncoding = "", 
    d_AddIconByType = "", 
    d_DefaultIcon = "", 
    d_HeaderName = "", 
    d_IndexHeadInsert = "", 
    d_IndexIgnore = ".", 
    d_IndexIgnoreReset = "", 
    d_IndexOptions = "", 
    d_IndexOrderDefault = "Ascending Name", 
    d_IndexStyleSheet = "", 
    d_ReadmeName = "", 
    
    d_ScriptLog = "", 
    d_ScriptLogBuffer = "1024", 
    d_ScriptLogLength = "10385760", 
    
    d_ScriptSock = "cgisock", 
    d_CGIDScriptTimeout = "", 
    
    d_DirectoryCheckHandler = "Off", 
    d_DirectoryIndex = "index.html", 
    d_IndexRedirect = "Off", 
    d_DirectorySlash = "On", 
    d_FallbackResource = "disabled", 
    
    d_PassEnv = "", 
    d_SetEnv = "", 
    d_UnsetEnv = "", 
    
    d_AddOutputFilterByType = "", 
    d_FilterChain = "", 
    d_FilterDeclare = "", 
    d_FilterProtocol = "", 
    d_FilterProvider = "", 
    d_FilterTrace = "", 
    
    d_ImapBase = "", --default:http://"servername"/
    d_ImapDefault = "nocontent", 
    d_ImapMenu = "formatted", 
    
    d_BufferedLogs = "Off", 
    d_CustomLog = "", 
    d_LogFormat = "\"%h %l %u %t \"%r\" %>s %b\"", 
    d_TransferLog = "", 
    
    d_AddCharset = "", 
    d_AddEncoding = "", 
    d_AddHandler = "", 
    d_AddInputFilter = "", 
    d_AddLanguage = "", 
    d_AddOutputFilter = "", 
    d_AddType = "", 
    d_DefaultLanguage = "", 
    d_ModMimeUsePathInfo = "Off", 
    d_MultiviewsMatch = "NegotiatedOnly", 
    d_RemoveCharset = "", 
    d_RemoveEncoding = "",
    d_RemoveHandler = "", 
    d_RemoveInputFilter = "", 
    d_RemoveLanguage = "",
    d_RemoveOutputFilter = "", 
    d_RemoveType = "", 
    d_TypesConfig = "conf/mime.types", 
    
    d_CacheNegotiatedDocs = "Off", 
    d_ForceLanguagePriority = "Prefer", 
    d_LanguagePriority = "", 
    
    d_ReflectorHeader = "", 

    d_KeptBodySize = "0", 
    
    d_BrowserMatch = "", 
    d_BrowserMatchNoCase = "", 
    d_SetEnvIf = "", 
    d_SetEnvIfExpr = "", 
    d_SetEnvIfNoCase = "", 
    
    d_ChrootDir = "", 
    d_Group = "", 
    d_Suexec = "", 
    d_User = "", 
    
    d_UserDir = "", 
    
    d_SSLCACertificateFile = "", 
    d_SSLCACertificatePath = "", 
    d_SSLCADNRequestFile = "", 
    d_SSLCADNRequestPath = "", 
    d_SSLCARevocationCheck = "", 
    d_SSLCARevocationFile = "", 
    d_SSLCARevocationPath = "", 
    d_SSLCertificateChainFile = "", 
    d_SSLCertificateFile = "", 
    d_SSLCertificateKeyFile = "", 
    d_SSLCipherSuite = "", 
    d_SSLCompression = "Off", 
    d_SSLCryptoDevice = "builtin", 
    d_SSLEngine = "Off", 
    d_SSLFIPS = "Off", 
    d_SSLHonorCipherOrder = "Off", 
    d_SSLInsecureRenegotiation = "Off", 
    d_SSLOCSPDefaultResponder = "", 
    d_SSLOCSPEnable = "Off", 
    d_SSLOCSPOverrideResponder = "Off", 
    d_SSLOCSPResponderTimeout = "10", 
    d_SSLOCSPResponseMaxAge = "-1", 
    d_SSLOCSPResponseTimeSkew = "300", 
    d_SSLOCSPUseRequestNonce = "On", 
    d_SSLOpenSSLConfCmd = "", 
    d_SSLOptions = "", 
    d_SSLPassPhraseDialog = "builtin", 
    d_SSLProtocol = "all", 
    d_SSLRandomSeed = "", 
    d_SSLRenegBufferSize = "131072", 
    d_SSLRequireSSL = "",
    d_SSLSessionCache = "None", 
    d_SSLSessionCacheTimeout = "300", 
    d_SSLSessionTicketKeyFile = "", 
    d_SSLSessionTickets = "On", 
    d_SSLSRPUnknownUserSeed = "", 
    d_SSLSRPVerifierFile = "", 
    d_SSLStaplingCache = "", 
    d_SSLStaplingErrorCacheTimeout = "600", 
    d_SSLStaplingFakeTryLater = "On", 
    d_SSLStaplingForceURL = "", 
    d_SSLStaplingResponderTimeout = "10", 
    d_SSLStaplingResponseMaxAge = "-1", 
    d_SSLStaplingResponseTimeSkew = "300", 
    d_SSLStaplingReturnResponderErrors = "On", 
    d_SSLStaplingStandardCacheTimeout = "3600", 
    d_SSLStrictSNIVHostCheck = "Off", 
    d_SSLUseStapling = "Off", 
    d_SSLVerifyClient = "None", 
    d_SSLVerifyDepth = "1", 
    d_SSLUserName = ""

}
