module Nginx_output where
import TypeFiles.Common
nginxOutput :: CommonWebserver
nginxOutput = CommonWebserver {
  vId = "1",
  vPid = "/run/nginx.pid",
  vRoot = "html",
  vIndex = "index.html index.htm",
  vErrorPages = [""],
  vKeepalive = "msie6",
  vKeepaliveTimeout = "65",
  vKeepaliveMaxRequests = "100",
  vSendfile = "off",
  vErrorLog = "/var/log/nginx/error.log",
  vAccessLog = "/var/log/nginx/access.log",
  vSSL = "off",
  vSSLCACertificate = "",
  vSSLCARevocationFile = "",
  vSSLCertificate = "",
  vSSLCertificateKey = "",
  vSSLCiphers = "HIGH:!aNULL:!MD5",
  vSSLPreferServerCiphers = "on",
  vSSLProtocols = "TLSv1 TLSv1.1 TLSv1.2",
  vSSLSessionTimeout = "5m",
  vSSLVerifyClient = "off",
  vSSLVerifyDepth = "1",
  vServers = [
    VServer {
        vServId = "1",
        vListen = ["80"],
        vServNames = ["example.com"],
        vServRoot = "/var/www/html_slow",
        vServIndex = "index.html",
        vServErrorPages = [""],
        vServKeepalive = "msie6",
        vServKeepaliveTimeout = "65",
        vServKeepaliveMaxRequests = "100",
        vServSendfile = "off",
        vServErrorLog = "/var/log/nginx/error.log",
        vServAccessLog = "logs/access.log combined",
        vServSSL = "off",
        vServSSLCACertificate = "",
        vServSSLCARevocationFile = "",
        vServSSLCertificate = "",
        vServSSLCertificateKey = "",
        vServSSLCiphers = "HIGH:!aNULL:!MD5",
        vServSSLPreferServerCiphers = "off",
        vServSSLProtocols = "TLSv1 TLSv1.1 TLSv1.2",
        vServSSLSessionTimeout = "5m",
        vServSSLVerifyClient = "off",
        vServSSLVerifyDepth = "1",
        vLocations = [
          VLocation {
              vLocId = "loc1",
              vLocationPath = "/",
              vLocRoot = "html",
              vLocIndex = "index.html",
              vLocErrorPages = "",
              vLocKeepalive = "msie6",
              vLocKeepaliveTimeout = "75s",
              vLocKeepaliveMaxRequests = "100",
              vLocSendfile = "off",
              vLocErrorLog = "logs/error.log error",
              vLocAccessLog = "logs/access.log combined"
              }
          ]
        },
    VServer {
      vServId = "2",
      vListen = ["443"],
      vServNames = ["example.com"],
      vServRoot = "/var/www/html_secure",
      vServIndex = "index.html",
      vServErrorPages = [""],
      vServKeepalive = "msie6",
      vServKeepaliveTimeout = "75s",
      vServKeepaliveMaxRequests = "100",
      vServSendfile = "off",
      vServErrorLog = "logs/error.log error",
      vServAccessLog = "logs/access.log combined",
      vServSSL = "on",
      vServSSLCACertificate = "",
      vServSSLCARevocationFile = "",
      vServSSLCertificate = "/etc/nginx/certs/cert.pem",
      vServSSLCertificateKey = "/etc/nginx/certs/cert.key",
      vServSSLCiphers = "HIGH:!aNULL:!MD5",
      vServSSLPreferServerCiphers = "off",
      vServSSLProtocols = "TLSv1 TLSv1.1 TLSv1.2",
      vServSSLSessionTimeout = "5m",
      vServSSLVerifyClient = "off",
      vServSSLVerifyDepth = "1",
      vLocations = []
      }
    ]
  }
